name: Test PRs on acc

on:
  workflow_call:
    inputs:
      pr_branch:
        description: 'The branch of the PR'
        required: true
        type: string
      base_sha:
        description: 'The base SHA of the PR'
        required: true
        type: string
      fetch_depth:
        description: 'The fetch depth for checkout'
        required: true
        type: number

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_branch }}
          fetch-depth: ${{ inputs.fetch_depth }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Copy default env variables
        run: cp .env.example .env
      - name: npm install
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          npm install
      - name: Verify base SHA
        run: |
          if ! git cat-file -e ${{ inputs.base_sha }}^{commit}; then
            echo "Base SHA ${{ inputs.base_sha }} does not exist."
            exit 1
          fi
      - name: Changed-files test coverage
        run: |
          if git diff --quiet ${{ inputs.base_sha }}; then
            echo "No changes detected since ${{ inputs.base_sha }}."
          else
            npm run test:changedsince ${{ inputs.base_sha }} -- --ci --runInBand --reportTestSuiteErrors=true
          fi
      - name: Lint
        run: npm run lint -- --max-warnings=0
      - name: TypeScript Compile
        run: npm run tsc
