# Reusable workflow, intended for use in both deploy workflows, and PR workflows

name: Run tests and build

on:
  workflow_call:
    inputs:
      concurrency_name:
        description: Identifier of a group to use to avoid concurrency
        required: false
        type: string
      enable_linting:
        description: Whether to skip linting
        required: false
        type: boolean
        default: true
      enable_tsc:
        description: Whether to enable TSC
        required: false
        type: boolean
        default: true
      enable_tests:
        description: Whether to skip tests
        required: false
        type: boolean
        default: true
      enable_build:
        description: Whether to skip build
        required: false
        type: boolean
        default: true
      enable_npmrc_echo:
        description: Whether to run the .npmrc echo step
        required: false
        type: boolean
        default: false
      enable_artifact_upload:
        description: Whether to upload the dist folder as an artifact
        required: false
        type: boolean
        default: true
      source_path:
        description: The path to the folder or file to deploy
        required: false
        type: string
        default: dist
      retention_days:
        description: How long to keep the build artifacts
        required: false
        type: number
        default: 2
      disable_artefacts:
        description: Whether to upload artefacts for deploying
        required: false
        type: boolean
        default: false

jobs:
  test_and_build:
    name: Test and Build
    concurrency:
      group: ${{ inputs.concurrency_name }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Setup .npmrc
        if: ${{ inputs.enable_npmrc_echo }}
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      - name: Install dependencies
        run: npm install
      - name: Lint
        if: ${{ inputs.enable_linting }}
        run: npm run lint -- --max-warnings=0
      - name: TSC
        if: ${{ inputs.enable_tsc }}
        run: npm run tsc;
      - name: Build
        if: ${{ inputs.enable_build }}
        run: npm run build
      - name: Run tests
        if: ${{ inputs.enable_tests }}
        run: npm test
      - name: Upload dist folder
        if: ${{ inputs.enable_build && inputs.disable_artefacts == false }}
        uses: actions/upload-artifact@v4
        with:
          name: build-and-terraform
          retention-days: ${{ inputs.retention_days }}
          path: ${{ inputs.source_path }}
