name: Preview Release

on:
  pull_request:
    branches:
      - master

jobs:

  preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Bump version
        id: bump_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true  # Only simulate the bump without actually tagging
          tag_prefix: ""
          release_branches: master

      - name: Show the new version
        run: 
          "echo The new version would be: ${{ steps.bump_version.outputs.new_tag }}"

      - name: Show changes
        run: |
          echo "Changes included in this release:"
          echo "${{ steps.bump_version.outputs.changelog }}"
