# Reusable workflow, intended for use in production deployments
name: Semantic release

on:
  workflow_call:
    inputs:
      environment_name:
        description: The Github environment containing all the variables needed
        required: false
        type: string
      enable_npmrc_echo:
        description: Whether to run the .npmrc echo step
        required: false
        type: boolean
        default: false
      enable_artifact_upload:
        description: Whether to upload the dist folder as an artifact
        required: false
        type: boolean
        default: true
      distPath:
        description: The path to the dist folder
        required: false
        type: string
        default: dist

jobs:
  release:
    name: Semantic release
    environment: "${{ inputs.environment_name }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download dist folder
        if: ${{ inputs.enable_artifact_upload }}
        uses: actions/download-artifact@v4
        with:
          name: dist-folder
          path: ${{ inputs.distPath }}
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Setup .npmrc
        if: ${{ inputs.enable_npmrc_echo }}
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      - name: Install dependencies
        run: npm install
      - name: Semantic release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run semantic-release
